spring.application.name=my-daily-memo-app
spring.datasource.url=jdbc:mysql://localhost:3306/memo_app
spring.datasource.username=root
spring.datasource.password=Naruto0211
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.jpa.hibernate.ddl-auto=update

vapid.public.key=BJNwvs_ytTbfi94zVcmvfrjNKIr3mGbWylR3xd-LnDmGQEJ7UD8qIOruTvyu6Dd4DpFWNbEJvzjg7sqT1buH_dc
vapid.private.key=y5Ey_7nag5MpLWL3jDZBbn_bA_I6VUrCgGQziGR7a2o